### ISSUE TITLE
For macos arm vm

### ISSUE THREAD

**Issue by LexiLominite** [roottusk/vapi#58]
_KEY" variable is not set. Defaulting to a blank string. 
WARN[0000] The "PUSHER_APP_CLUSTER" variable is not set. Defaulting to a blank string. 
WARN[0000] /home/parallels/APILABs/vapi/docker-compose.yml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion 
[+] Running 5/5
 ✔ Network vapi_default                                                                                                                                      Created                                                                    0.1s 
 ✔ Container vapi-db-1                                                                                                                                       Started                                                                    0.2s 
 ✔ Container vapi-www-1                                                                                                                                      Started                                                                    0.4s 
 ✔ Container vapi-phpmyadmin-1                                                                                                                               Started                                                                    0.3s 
 ! phpmyadmin The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requeste

**Comment by LexiLominite** [comment]
Where should i change the configuration from

**Comment by LexiLominite** [comment]
change your docker-compose.yml to below so that it will retreive arm64 compatible phpmyadmin

```
version: "3.1"
services:
    www:
        build: .
        ports: 
            - "8000:80"
        volumes:
            - ./vapi:/var/www/html/vapi
        links:
            - db
        networks:
            - default
        environment:
          APP_NAME: Laravel
          APP_ENV: local
          APP_KEY: "base64:JUXTsCKQubRlvxGv6sVwkFL2rJ/gSksD4B/68948Mww:"
          APP_DEBUG: "true"
          APP_URL: http://vapi.test
          SERVER_PORT: 80
          LOG_CHANNEL: errorlog
          LOG_LEVEL: debug
          DB_CONNECTION: mysql
          DB_HOST: db
          DB_PORT: 3306
          DB_DATABASE: vapi
          DB_USERNAME: root
          DB_PASSWORD: vapi123456
          BROADCAST_DRIVER: log
          CACHE_DRIVER: file
          FILESYSTEM_DRIVER: local
          QUEUE_CONNECTION: sync
          SESSION_DRIVER: file
          SESSION_LIFETIME: 120
          MEMCACHED_HOST: 127.0.0.1
          REDIS_HOST: 127.0.0.1
          REDIS_PASSWORD: ""
          REDIS_PORT: 6379
          MAIL_MAILER: smtp
          MAIL_HOST: mailhog
          MAIL_PORT: 1025
          MAIL_USERNAME: ""
          MAIL_PASSWORD: ""
          MAIL_ENCRYPTION: ""
          MAIL_FROM_ADDRESS: ""
          MAIL_FROM_NAME: "${APP_NAME}"
          AWS_ACCESS_KEY_ID:
          AWS_SECRET_ACCESS_KEY:
          AWS_DEFAULT_REGION: us-east-1
          AWS_BUCKET:
          AWS_USE_PATH_STYLE_ENDPOINT: "false"
          PUSHER_APP_ID:
          PUSHER_APP_KEY:
          PUSHER_APP_SECRET:
          PUSHER_APP_CLUSTER: mt1
          MIX_PUSHER_APP_KEY: "${PUSHER_APP_KEY}"
          MIX_PUSHER_APP_CLUSTER: "${PUSHER_APP_CLUSTER}"
    db:
        image: mysql:8.0
        ports: 
            - "3306:3306"
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_DATABASE: vapi
            MYSQL_USER: vapi
            MYSQL_PASSWORD: vapi123456
            MYSQL_ROOT_PASSWORD: vapi123456
        volumes:
            - ./database:/docker-entrypoint-initdb.d
            - ./conf:/etc/mysql/conf.d
            - persistent:/var/lib/mysql
        networks:
            - default
    phpmyadmin:
        image: arm64v8/phpmyadmin
        platform: linux/arm64/v8
        links: 
            - db:db
        ports:
            - 8001:80
        environment:
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: vapi123456
volumes:
    persistent:
networks:
    default:

```

Change  you DockerFile to this so that it will use php from arm64

```
# Use an ARM64-compatible base image
FROM arm64v8/php:7.4-apache

# Install necessary dependencies
RUN apt-get update && \
    apt-get install -y libzip-dev zlib1g-dev wget unzip && \
    rm -rf /var/lib/apt/lists/*

# Download and install phpMyAdmin
RUN wget https://files.phpmyadmin.net/phpMyAdmin/latest/phpMyAdmin-latest-all-languages.zip -O /tmp/phpmyadmin.zip && \
    unzip /tmp/phpmyadmin.zip -d /var/www/html/ && \
    mv /var/www/html/phpMyAdmin-* /var/www/html/phpmyadmin && \
    rm /tmp/phpmyadmin.zip

# Set appropriate permissions
RUN chown -R www-data:www-data /var/www/html/phpmyadmin && \
    chmod -R 755 /var/www/html/phpmyadmin

# Expose port 80
EXPOSE 80

# Set the default command to start Apache
CMD ["apache2-foreground"]

```
